apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-go-gke
---
apiVersion: v1
kind: Service
metadata:
  name: api-go-gke
spec:
  selector:
    name: api-go-gke
  clusterIP: None
  ports:
    - name: api-go-gke
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: api-go-gke
  annotations:
    'consul.hashicorp.com/connect-inject': 'true'
  labels:
    name: api-go-gke
spec:
  serviceAccountName: api-go-gke
  containers:
    - name: api-go-gke
      image: index.docker.io/tkaburagi/api-go-auth_users-table:latest
      ports:
        - containerPort: 8080
          name: http
      env:
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: username
      - name: MYSQL_PASS
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
      - name: MYSQL_URL
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: url