global:
  name: consul
  datacenter: dc1-gke
  image: consul:1.9.0
  imageK8S: hashicorp/consul-k8s:0.22.0
  tls:
   enabled: true
  federation:
   enabled: true
   createFederationSecret: true
#  acls:
#   manageSystemACLs: true
#   createReplicationToken: true
#  gossipEncryption:
#   secretName: consul-gossip-encryption-key
#   secretKey: key

connectInject:
  enabled: true
client:
  enabled: true
meshGateway:
  enabled: true
ui:
  service:
    type: LoadBalancer