global:
  name: consul
  image: consul:1.9.1
  imageK8S: hashicorp/consul-k8s:0.22.0
  datacenter: dc1-gke
  federation:
    enabled: true
    createFederationSecret: true
  tls:
    enabled: true
meshGateway:
 enabled: true
connectInject:
 enabled: true
client:
  enabled: true
ui:
  service:
    type: LoadBalancer
syncCatalog:
  enabled: true
  toConsul: true
  toK8S: true